[build]
builder = "nixpacks"

[deploy]
startCommand = "mkdir -p storage/framework/{sessions,views,cache} && chmod -R 775 storage && php artisan migrate --force && php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/"
healthcheckTimeout = 600
restartPolicyType = "on_failure"

[build.steps]
preBuild = "npm ci"
build = "npm run build"

[variables]
APP_NAME = "نظام الفواتير"
APP_ENV = "production"
APP_DEBUG = "false"
APP_KEY = "base64:eHbq6Ekz/qcbsfMO6iDNMoE3Nwt0TkEw+YYcdKWMzUc="
APP_LOCALE = "ar"
APP_FALLBACK_LOCALE = "ar"
APP_FAKER_LOCALE = "ar_SA"
LOG_CHANNEL = "stack"
LOG_LEVEL = "debug"
DB_CONNECTION = "mysql"
DB_HOST = "127.0.0.1"
DB_PORT = "3306"
DB_DATABASE = "invoice"
DB_USERNAME = "root"
DB_PASSWORD = "123456"
SESSION_DRIVER = "file"
SESSION_LIFETIME = "120"
CACHE_DRIVER = "file"
QUEUE_CONNECTION = "sync"
MAIL_MAILER = "log"
MAIL_FROM_ADDRESS = "noreply@yourdomain.com"
MAIL_FROM_NAME = "نظام الفواتير"
